### PR TITLE
Java11 HttpRequest

### PR DESCRIPTION
**Pull request by takesson**
- Forced BASIC authentication if username available
- Connect timeout no longer configurable
- Keep-Alive handled by http client (private information should not be
able to leak, each request is separate regardless of reusing transport).

### CODE REVIEW

**Comment by takesson** [comment]
@solsson Are you using restclient at this time? 
Next step is to add POST support. However, the value of abstracting the HTTP requests has significantly decreased since the Java 11 API seems good...

**Comment by solsson** [comment]
> Are you using restclient at this time?

No, moved on to Quarkus' abstractions. Which seem to be based on apache HC.

> Next step is to add POST support. However, the value of abstracting the HTTP requests has significantly decreased since the Java 11 API seems good...

I agree that with the introduction of POST it's better to evaluate new alternatives. There might even be good 3rd party abstractions these days. If they turn out to work this lib can be discarded.

**Comment by takesson** [comment]
> > Are you using restclient at this time?
> 
> No, moved on to Quarkus' abstractions. Which seem to be based on apache HC.

Which Quarkus abstractions? Kafka-specific?

> 
> > Next step is to add POST support. However, the value of abstracting the HTTP requests has significantly decreased since the Java 11 API seems good...
> 
> I agree that with the introduction of POST it's better to evaluate new alternatives. There might even be good 3rd party abstractions these days. If they turn out to work this lib can be discarded.

I have actually been looking for some Webhook-emitter library... seen anything sane?

**Comment by takesson** [comment]
Quarkus really likes reactive and Apache HC is not great for reactive. I have never looked into Netty.

**Review by solsson — APPROVED** [review]
I can't really review the new impl. The test coverage from the original impl is quite limited. Given that it probably won't be scoped up beyond the current use cases I think it's fine.

**Pull request merged**
